// 雅思高频词库：每个词都带音标、词性、中文、谐音梗、雅思风格例句和常用搭配
// 谐音梗只是「敲门砖」，帮你第一次把词塞进脑子；真正记牢还要靠例句和搭配。
window.TOPICS = [
  { id: "env", name: "环境", emoji: "🌍", color: "#22c55e" },
  { id: "edu", name: "教育", emoji: "🎓", color: "#3b82f6" },
  { id: "tech", name: "科技", emoji: "💻", color: "#a855f7" },
  { id: "health", name: "健康", emoji: "🏥", color: "#ef4444" },
  { id: "society", name: "社会与工作", emoji: "🏙️", color: "#f59e0b" },
  { id: "culture", name: "文化与媒体", emoji: "🎭", color: "#ec4899" },
  { id: "academic", name: "学术万能词", emoji: "📝", color: "#14b8a6" }
];

window.WORDS = [
  // ───────── 环境 ─────────
  { id: 1, topic: "env", word: "pollution", ipa: "/pəˈluːʃn/", pos: "n.", cn: "污染",
    pun: "泼露身", punStory: "脏水「泼」到「露」出来的「身」上，这就是污染。",
    example: "Air pollution has become a serious problem in many large cities.",
    exampleCn: "空气污染在许多大城市已成为严重问题。",
    collocations: ["air / water pollution", "reduce pollution", "a major source of pollution"] },
  { id: 2, topic: "env", word: "sustainable", ipa: "/səˈsteɪnəbl/", pos: "adj.", cn: "可持续的",
    pun: "撒得能播", punStory: "「撒」下的种子明年还「能播」，年年有收成，就是可持续。",
    example: "Governments should invest in sustainable energy sources such as wind and solar power.",
    exampleCn: "政府应投资风能、太阳能等可持续能源。",
    collocations: ["sustainable development", "sustainable energy", "environmentally sustainable"] },
  { id: 3, topic: "env", word: "deforestation", ipa: "/diːˌfɒrɪˈsteɪʃn/", pos: "n.", cn: "森林砍伐",
    pun: "弟把森林砍得省", punStory: "de- 表示「去掉」，forest 是森林：把森林去掉 = 砍伐森林。记成「弟」（de）把 forest 砍了想「省」（-tion）钱。",
    example: "Deforestation is one of the main causes of climate change.",
    exampleCn: "森林砍伐是气候变化的主要原因之一。",
    collocations: ["large-scale deforestation", "combat deforestation", "deforestation in the Amazon"] },
  { id: 4, topic: "env", word: "emission", ipa: "/ɪˈmɪʃn/", pos: "n.", cn: "排放（物）",
    pun: "一米深", punStory: "工厂烟囱冒出「一米深」的黑烟，那就是排放。",
    example: "Countries have agreed to cut carbon emissions by 40% before 2030.",
    exampleCn: "各国同意在 2030 年前减少 40% 的碳排放。",
    collocations: ["carbon emissions", "greenhouse gas emissions", "cut / reduce emissions"] },
  { id: 5, topic: "env", word: "renewable", ipa: "/rɪˈnjuːəbl/", pos: "adj.", cn: "可再生的",
    pun: "日纽阿宝", punStory: "re（再）+ new（新）+ able（能）= 能再变新。太阳「日」「纽」约每天升起，永远用不完。",
    example: "Renewable energy now accounts for a growing share of electricity production.",
    exampleCn: "可再生能源在发电中的占比正在增长。",
    collocations: ["renewable energy / resources", "switch to renewables"] },
  { id: 6, topic: "env", word: "conserve", ipa: "/kənˈsɜːv/", pos: "v.", cn: "保护；节约（资源）",
    pun: "啃瑟夫", punStory: "宁可「啃」干粮、冻得「瑟瑟」发抖，也要把暖气关了节约能源。",
    example: "We must conserve water during the dry season.",
    exampleCn: "旱季我们必须节约用水。",
    collocations: ["conserve energy / water", "conserve natural resources", "conservation (n.)"] },
  { id: 7, topic: "env", word: "ecosystem", ipa: "/ˈiːkəʊsɪstəm/", pos: "n.", cn: "生态系统",
    pun: "一口系统", punStory: "大鱼「一口」吃小鱼，小鱼一口吃虾米，这一口口吃出来的「系统」就是生态系统。",
    example: "Plastic waste is destroying marine ecosystems.",
    exampleCn: "塑料垃圾正在破坏海洋生态系统。",
    collocations: ["fragile ecosystem", "marine ecosystem", "damage the ecosystem"] },
  { id: 8, topic: "env", word: "drought", ipa: "/draʊt/", pos: "n.", cn: "干旱",
    pun: "抓土", punStory: "干旱的时候地里没水，一伸手只能「抓」到干「土」。",
    example: "The region has suffered from severe drought for three consecutive years.",
    exampleCn: "该地区已连续三年遭受严重干旱。",
    collocations: ["severe / prolonged drought", "drought-stricken areas"] },
  { id: 9, topic: "env", word: "contaminate", ipa: "/kənˈtæmɪneɪt/", pos: "v.", cn: "污染；弄脏",
    pun: "啃它米内特", punStory: "「啃」了「它」的「米」，「内」脏「特」别难受——米被污染了。",
    example: "Chemical waste from the factory has contaminated the river.",
    exampleCn: "工厂的化学废料污染了这条河。",
    collocations: ["contaminated water / food", "contamination (n.)"] },
  { id: 10, topic: "env", word: "habitat", ipa: "/ˈhæbɪtæt/", pos: "n.", cn: "栖息地",
    pun: "哈比它", punStory: "「哈比」人住的那个特别的地方，就是「它」的栖息地。",
    example: "Urban expansion is destroying the natural habitat of many species.",
    exampleCn: "城市扩张正在破坏许多物种的自然栖息地。",
    collocations: ["natural habitat", "habitat loss / destruction", "wildlife habitat"] },

  // ───────── 教育 ─────────
  { id: 11, topic: "edu", word: "curriculum", ipa: "/kəˈrɪkjələm/", pos: "n.", cn: "课程（体系）",
    pun: "课里可冷", punStory: "「课里可冷」了——课程排得满满的，教室里冷冰冰的。",
    example: "Schools should include financial education in the national curriculum.",
    exampleCn: "学校应把理财教育纳入国家课程。",
    collocations: ["the school curriculum", "core curriculum", "curriculum design"] },
  { id: 12, topic: "edu", word: "compulsory", ipa: "/kəmˈpʌlsəri/", pos: "adj.", cn: "义务的；强制的",
    pun: "肯跑死你", punStory: "强制体育课：「肯」定「跑死你」，不跑也得跑。",
    example: "In most countries, education is compulsory until the age of 16.",
    exampleCn: "在多数国家，16 岁之前的教育是义务性的。",
    collocations: ["compulsory education", "make sth compulsory", "compulsory subjects"] },
  { id: 13, topic: "edu", word: "literacy", ipa: "/ˈlɪtərəsi/", pos: "n.", cn: "读写能力",
    pun: "里特累死", punStory: "letter 是字母，literacy 就是认字母的能力。小「里特」学认字「累死」了。",
    example: "Adult literacy rates have improved dramatically over the past decade.",
    exampleCn: "过去十年成人识字率显著提高。",
    collocations: ["literacy rate", "digital / financial literacy", "illiteracy (n.) 文盲"] },
  { id: 14, topic: "edu", word: "scholarship", ipa: "/ˈskɒləʃɪp/", pos: "n.", cn: "奖学金",
    pun: "死磕拉 ship", punStory: "scholar 是学者。「死磕」学习，才能「拉」到奖学金，坐上出国的「ship」。",
    example: "She won a full scholarship to study abroad.",
    exampleCn: "她获得了出国留学的全额奖学金。",
    collocations: ["win / receive a scholarship", "full scholarship", "scholarship programme"] },
  { id: 15, topic: "edu", word: "tuition", ipa: "/tjuˈɪʃn/", pos: "n.", cn: "学费；讲授",
    pun: "丢一身", punStory: "交完学费，钱「丢」得「一身」轻，口袋全空。",
    example: "Rising tuition fees have made university less accessible to poorer students.",
    exampleCn: "不断上涨的学费让贫困学生更难上大学。",
    collocations: ["tuition fees", "private tuition", "free tuition"] },
  { id: 16, topic: "edu", word: "discipline", ipa: "/ˈdɪsəplɪn/", pos: "n.", cn: "纪律；学科",
    pun: "弟死泼冷", punStory: "「弟」弟不守纪律，被老师「泼冷」水，「死」定了。",
    example: "Strict discipline in schools does not necessarily lead to better results.",
    exampleCn: "学校里严格的纪律不一定带来更好的成绩。",
    collocations: ["strict discipline", "self-discipline", "academic discipline 学科"] },
  { id: 17, topic: "edu", word: "peer", ipa: "/pɪə(r)/", pos: "n.", cn: "同龄人；同伴",
    pun: "皮儿", punStory: "一群「皮」孩「儿」凑在一起，那就是同龄人。",
    example: "Teenagers are heavily influenced by their peers.",
    exampleCn: "青少年深受同龄人影响。",
    collocations: ["peer pressure 同伴压力", "peer group", "peer review"] },
  { id: 18, topic: "edu", word: "motivation", ipa: "/ˌməʊtɪˈveɪʃn/", pos: "n.", cn: "动力；积极性",
    pun: "磨题为神", punStory: "为了「成神」拼命「磨题」，这股劲儿就是动力。",
    example: "Lack of motivation is a common reason why students drop out.",
    exampleCn: "缺乏动力是学生辍学的常见原因。",
    collocations: ["lack of motivation", "motivate (v.)", "motivated students"] },
  { id: 19, topic: "edu", word: "plagiarism", ipa: "/ˈpleɪdʒərɪzəm/", pos: "n.", cn: "抄袭",
    pun: "不累这人", punStory: "写论文「不累」？「这人」肯定是抄的。",
    example: "Universities use software to detect plagiarism in student essays.",
    exampleCn: "大学使用软件检测学生论文中的抄袭。",
    collocations: ["commit plagiarism", "plagiarise (v.)", "accused of plagiarism"] },
  { id: 20, topic: "edu", word: "vocational", ipa: "/vəʊˈkeɪʃənl/", pos: "adj.", cn: "职业的（培训）",
    pun: "我开训呢", punStory: "「我开」始职业培「训呢」——学的是能直接上岗的手艺。",
    example: "Vocational training helps young people gain practical skills for work.",
    exampleCn: "职业培训帮助年轻人获得实用的工作技能。",
    collocations: ["vocational training / education", "vocational courses"] },

  // ───────── 科技 ─────────
  { id: 21, topic: "tech", word: "innovation", ipa: "/ˌɪnəˈveɪʃn/", pos: "n.", cn: "创新",
    pun: "in 呢为新", punStory: "「in」（里面）「呢」，为了「新」——从里面翻出新东西，就是创新。",
    example: "Technological innovation has transformed the way we communicate.",
    exampleCn: "技术创新改变了我们的交流方式。",
    collocations: ["technological innovation", "encourage innovation", "innovative (adj.)"] },
  { id: 22, topic: "tech", word: "artificial", ipa: "/ˌɑːtɪˈfɪʃl/", pos: "adj.", cn: "人造的；人工的",
    pun: "阿提 fish 哦", punStory: "「阿提」提着一条假「fish」，「哦」，原来是人造的。",
    example: "Artificial intelligence is likely to replace many routine jobs.",
    exampleCn: "人工智能可能会取代许多重复性工作。",
    collocations: ["artificial intelligence (AI)", "artificial light", "artificial flavours"] },
  { id: 23, topic: "tech", word: "automation", ipa: "/ˌɔːtəˈmeɪʃn/", pos: "n.", cn: "自动化",
    pun: "奥特美神", punStory: "「奥特」曼一秒「美」丽变「神」，全自动，不用手动。",
    example: "Automation in factories has led to job losses among unskilled workers.",
    exampleCn: "工厂自动化导致非技术工人失业。",
    collocations: ["automation of manufacturing", "automate (v.)", "automated systems"] },
  { id: 24, topic: "tech", word: "obsolete", ipa: "/ˈɒbsəliːt/", pos: "adj.", cn: "过时的；淘汰的",
    pun: "哦不 so 累特", punStory: "「哦不」，这方法「so 累特」（太累了），早该淘汰了。",
    example: "Many skills will become obsolete as technology develops.",
    exampleCn: "随着技术发展，许多技能会变得过时。",
    collocations: ["become obsolete", "obsolete technology", "render sth obsolete"] },
  { id: 25, topic: "tech", word: "surveillance", ipa: "/sɜːˈveɪləns/", pos: "n.", cn: "监视；监控",
    pun: "瑟微冷死", punStory: "被摄像头盯着，「瑟瑟」发抖，「微」微「冷死」了。",
    example: "Mass surveillance raises serious concerns about privacy.",
    exampleCn: "大规模监控引发了对隐私的严重担忧。",
    collocations: ["surveillance cameras", "under surveillance", "mass surveillance"] },
  { id: 26, topic: "tech", word: "cyber", ipa: "/ˈsaɪbə(r)/", pos: "adj.", cn: "网络的",
    pun: "赛博", punStory: "「赛博」朋克——就是网络世界的那种朋克风。",
    example: "Cyber attacks on banks are becoming more sophisticated.",
    exampleCn: "针对银行的网络攻击越来越复杂。",
    collocations: ["cyber attack / crime", "cyber security", "cyberbullying 网络霸凌"] },
  { id: 27, topic: "tech", word: "breakthrough", ipa: "/ˈbreɪkθruː/", pos: "n.", cn: "突破",
    pun: "不累克死路", punStory: "break（打破）+ through（穿过）：「不累」，「克」掉「死路」冲过去——突破！",
    example: "Scientists have made a major breakthrough in cancer treatment.",
    exampleCn: "科学家在癌症治疗上取得重大突破。",
    collocations: ["make a breakthrough", "a major / scientific breakthrough"] },
  { id: 28, topic: "tech", word: "addictive", ipa: "/əˈdɪktɪv/", pos: "adj.", cn: "使人上瘾的",
    pun: "呃弟可提夫", punStory: "「呃」，「弟」弟「可提夫」——手机一天到晚提在手里，上瘾了。",
    example: "Social media is designed to be addictive.",
    exampleCn: "社交媒体的设计就是为了让人上瘾。",
    collocations: ["highly addictive", "addiction (n.)", "addicted to (adj.)"] },
  { id: 29, topic: "tech", word: "efficiency", ipa: "/ɪˈfɪʃnsi/", pos: "n.", cn: "效率",
    pun: "一飞神速", punStory: "「一飞」就是「神速」——效率高得飞起。",
    example: "Computers have greatly improved the efficiency of office work.",
    exampleCn: "计算机大大提高了办公效率。",
    collocations: ["improve efficiency", "energy efficiency", "efficient (adj.)"] },
  { id: 30, topic: "tech", word: "virtual", ipa: "/ˈvɜːtʃuəl/", pos: "adj.", cn: "虚拟的",
    pun: "我戳哦", punStory: "「我戳」一下，「哦」，手穿过去了——原来是虚拟的。",
    example: "Virtual classrooms allow students to learn from anywhere.",
    exampleCn: "虚拟课堂让学生可以在任何地方学习。",
    collocations: ["virtual reality (VR)", "virtual classroom", "virtually (adv.) 几乎"] },

  // ───────── 健康 ─────────
  { id: 31, topic: "health", word: "obesity", ipa: "/əʊˈbiːsəti/", pos: "n.", cn: "肥胖（症）",
    pun: "哦比死弟", punStory: "「哦」，「比」谁都胖的「死弟」弟，胖得爬不起来。",
    example: "Childhood obesity has doubled in the last twenty years.",
    exampleCn: "儿童肥胖率在过去二十年翻了一倍。",
    collocations: ["childhood obesity", "obesity rates", "obese (adj.)"] },
  { id: 32, topic: "health", word: "nutrition", ipa: "/njuˈtrɪʃn/", pos: "n.", cn: "营养",
    pun: "牛吹神", punStory: "「牛」奶广告把营养「吹」上「神」坛。",
    example: "Good nutrition is essential for children's development.",
    exampleCn: "良好的营养对儿童发育至关重要。",
    collocations: ["poor / good nutrition", "nutritious (adj.)", "nutritional value"] },
  { id: 33, topic: "health", word: "sedentary", ipa: "/ˈsedntri/", pos: "adj.", cn: "久坐的",
    pun: "傻等吹", punStory: "「傻傻」地坐着「等」空调「吹」，一坐一整天。",
    example: "A sedentary lifestyle increases the risk of heart disease.",
    exampleCn: "久坐的生活方式会增加心脏病风险。",
    collocations: ["sedentary lifestyle", "sedentary jobs"] },
  { id: 34, topic: "health", word: "epidemic", ipa: "/ˌepɪˈdemɪk/", pos: "n.", cn: "流行病；泛滥",
    pun: "哎病得密集", punStory: "「哎」，「病得」太「密集」了，一片一片倒——流行病。",
    example: "Obesity has become an epidemic in many developed countries.",
    exampleCn: "肥胖在许多发达国家已成为一种流行病。",
    collocations: ["an epidemic of sth", "flu epidemic", "pandemic 大流行"] },
  { id: 35, topic: "health", word: "immune", ipa: "/ɪˈmjuːn/", pos: "adj.", cn: "免疫的；不受影响的",
    pun: "一秒 immune", punStory: "抗体「一秒」（i-mmune）上线，病毒立刻免疫。",
    example: "Regular exercise strengthens the immune system.",
    exampleCn: "规律运动增强免疫系统。",
    collocations: ["immune system", "immune to sth", "immunity (n.)"] },
  { id: 36, topic: "health", word: "diagnose", ipa: "/ˈdaɪəɡnəʊz/", pos: "v.", cn: "诊断",
    pun: "呆哥 no 死", punStory: "医生一诊断：「呆哥」，「no」，不会「死」，放心。",
    example: "Early diagnosis can greatly improve survival rates.",
    exampleCn: "早期诊断能大大提高存活率。",
    collocations: ["be diagnosed with", "diagnosis (n.)", "early diagnosis"] },
  { id: 37, topic: "health", word: "symptom", ipa: "/ˈsɪmptəm/", pos: "n.", cn: "症状",
    pun: "新疼", punStory: "身上出现「新」的「疼」，那就是症状。",
    example: "Fatigue is a common symptom of stress.",
    exampleCn: "疲劳是压力的常见症状。",
    collocations: ["show symptoms", "a symptom of", "symptoms include..."] },
  { id: 38, topic: "health", word: "hygiene", ipa: "/ˈhaɪdʒiːn/", pos: "n.", cn: "卫生",
    pun: "嗨，净！", punStory: "「嗨」，「净」一点——讲卫生！",
    example: "Poor hygiene in hospitals can spread infections.",
    exampleCn: "医院卫生条件差会传播感染。",
    collocations: ["personal hygiene", "poor hygiene", "hygienic (adj.)"] },
  { id: 39, topic: "health", word: "therapy", ipa: "/ˈθerəpi/", pos: "n.", cn: "治疗；疗法",
    pun: "赛拉皮", punStory: "去做「拉皮」的疗法，比「赛」谁更年轻。",
    example: "Music therapy is increasingly used to treat anxiety.",
    exampleCn: "音乐疗法越来越多地用于治疗焦虑。",
    collocations: ["physical therapy", "undergo therapy", "therapist (n.)"] },
  { id: 40, topic: "health", word: "fatigue", ipa: "/fəˈtiːɡ/", pos: "n.", cn: "疲劳",
    pun: "乏提个", punStory: "「乏」得连「个」头都「提」不起来——疲劳。",
    example: "Long working hours often result in chronic fatigue.",
    exampleCn: "长时间工作常导致慢性疲劳。",
    collocations: ["chronic fatigue", "suffer from fatigue", "mental fatigue"] },

  // ───────── 社会与工作 ─────────
  { id: 41, topic: "society", word: "inequality", ipa: "/ˌɪnɪˈkwɒləti/", pos: "n.", cn: "不平等",
    pun: "一你阔了提", punStory: "in（不）+ equal（平等）。「一」看「你阔了」，我却没「提」高——不平等。",
    example: "Income inequality has widened in recent decades.",
    exampleCn: "近几十年收入不平等加剧了。",
    collocations: ["income / social inequality", "gender inequality", "reduce inequality"] },
  { id: 42, topic: "society", word: "welfare", ipa: "/ˈwelfeə(r)/", pos: "n.", cn: "福利；幸福",
    pun: "喂 fair", punStory: "well（好）+ fare（过日子）。国家把大家「喂」得「fair」（公平），就是福利。",
    example: "The government spends billions on social welfare each year.",
    exampleCn: "政府每年在社会福利上投入数十亿。",
    collocations: ["social welfare", "welfare state", "welfare benefits"] },
  { id: 43, topic: "society", word: "urbanisation", ipa: "/ˌɜːbənaɪˈzeɪʃn/", pos: "n.", cn: "城市化",
    pun: "饿本奶贼神", punStory: "urban 是城市。进城之后「饿」着肚子攒「本」钱买「奶」，「贼神」奇——城市化生活。",
    example: "Rapid urbanisation has put pressure on housing and transport.",
    exampleCn: "快速城市化给住房和交通带来压力。",
    collocations: ["rapid urbanisation", "urban areas", "rural-to-urban migration"] },
  { id: 44, topic: "society", word: "commute", ipa: "/kəˈmjuːt/", pos: "v./n.", cn: "通勤",
    pun: "可谬特", punStory: "每天两小时上班路，「可谬特」（可太荒谬）了——通勤。",
    example: "Many people commute for over an hour each way.",
    exampleCn: "许多人单程通勤超过一小时。",
    collocations: ["commute to work", "a long commute", "commuter (n.)"] },
  { id: 45, topic: "society", word: "unemployment", ipa: "/ˌʌnɪmˈplɔɪmənt/", pos: "n.", cn: "失业",
    pun: "俺 no 破落门", punStory: "un（不）+ employ（雇用）。「俺」没工作，「no」钱，家里「破落门」。",
    example: "Youth unemployment remains a major challenge for the economy.",
    exampleCn: "青年失业仍是经济面临的重大挑战。",
    collocations: ["unemployment rate", "youth unemployment", "unemployed (adj.)"] },
  { id: 46, topic: "society", word: "immigrant", ipa: "/ˈɪmɪɡrənt/", pos: "n.", cn: "移民（移入者）",
    pun: "一米哥 run 特", punStory: "「一米哥」「run」到国外定居——移民。",
    example: "Immigrants contribute significantly to the economy of their host country.",
    exampleCn: "移民对所在国经济贡献巨大。",
    collocations: ["illegal immigrants", "immigration (n.)", "emigrate 移出 vs immigrate 移入"] },
  { id: 47, topic: "society", word: "poverty", ipa: "/ˈpɒvəti/", pos: "n.", cn: "贫穷",
    pun: "破屋提", punStory: "住在「破屋」里，每天「提」水桶——贫穷。",
    example: "Millions of children still live in extreme poverty.",
    exampleCn: "数百万儿童仍生活在极端贫困中。",
    collocations: ["live in poverty", "poverty line", "alleviate poverty"] },
  { id: 48, topic: "society", word: "crime", ipa: "/kraɪm/", pos: "n.", cn: "犯罪",
    pun: "快埋", punStory: "犯了罪，证据「快埋」起来。",
    example: "CCTV cameras have helped to reduce crime rates in city centres.",
    exampleCn: "监控摄像头帮助降低了市中心的犯罪率。",
    collocations: ["crime rate", "commit a crime", "criminal (n./adj.)"] },
  { id: 49, topic: "society", word: "globalisation", ipa: "/ˌɡləʊbəlaɪˈzeɪʃn/", pos: "n.", cn: "全球化",
    pun: "够楼抱来贼神", punStory: "global 是全球。「够」在「楼」下就能「抱来」全球货，「贼神」——全球化。",
    example: "Globalisation has made the world more interconnected than ever.",
    exampleCn: "全球化让世界比以往任何时候都更紧密相连。",
    collocations: ["economic globalisation", "the effects of globalisation", "global (adj.)"] },
  { id: 50, topic: "society", word: "ambitious", ipa: "/æmˈbɪʃəs/", pos: "adj.", cn: "有野心的；雄心勃勃的",
    pun: "俺必胜", punStory: "「俺必胜」！——一听就野心勃勃。",
    example: "The government has set an ambitious target to eliminate poverty by 2040.",
    exampleCn: "政府设定了到 2040 年消除贫困的雄心目标。",
    collocations: ["an ambitious plan / target", "ambition (n.)"] },

  // ───────── 文化与媒体 ─────────
  { id: 51, topic: "culture", word: "heritage", ipa: "/ˈherɪtɪdʒ/", pos: "n.", cn: "遗产（文化）",
    pun: "嘿立提纸", punStory: "「嘿」，爷爷「立」了遗嘱，「提」着「纸」说：这是留给你的遗产。",
    example: "The government should protect the country's cultural heritage.",
    exampleCn: "政府应保护国家的文化遗产。",
    collocations: ["cultural heritage", "World Heritage Site", "preserve heritage"] },
  { id: 52, topic: "culture", word: "censorship", ipa: "/ˈsensəʃɪp/", pos: "n.", cn: "审查（制度）",
    pun: "闪色 ship", punStory: "审查员一挥手：「闪」掉那艘「色」情「ship」——审查。",
    example: "Some argue that censorship of the internet limits freedom of speech.",
    exampleCn: "有人认为网络审查限制了言论自由。",
    collocations: ["media censorship", "censor (v.)", "strict censorship"] },
  { id: 53, topic: "culture", word: "bias", ipa: "/ˈbaɪəs/", pos: "n.", cn: "偏见",
    pun: "拜饿死", punStory: "宁可「饿死」也不「拜」——偏见有多深。",
    example: "News reports often show a clear political bias.",
    exampleCn: "新闻报道常表现出明显的政治偏见。",
    collocations: ["gender bias", "biased (adj.)", "without bias"] },
  { id: 54, topic: "culture", word: "celebrity", ipa: "/səˈlebrəti/", pos: "n.", cn: "名人",
    pun: "谁累不累提", punStory: "「谁累不累」，拍戏「提」神——名人的生活。",
    example: "Young people often see celebrities as role models.",
    exampleCn: "年轻人常把名人当作榜样。",
    collocations: ["celebrity culture", "a celebrity chef", "become a celebrity"] },
  { id: 55, topic: "culture", word: "mainstream", ipa: "/ˈmeɪnstriːm/", pos: "n./adj.", cn: "主流（的）",
    pun: "们死追", punStory: "main（主要）+ stream（溪流）= 主流。大家「们」都「死追」的东西，就是主流。",
    example: "Electric cars have moved from niche products into the mainstream.",
    exampleCn: "电动车已从小众产品进入主流。",
    collocations: ["mainstream media", "enter the mainstream", "mainstream culture"] },
  { id: 56, topic: "culture", word: "tradition", ipa: "/trəˈdɪʃn/", pos: "n.", cn: "传统",
    pun: "吹地神", punStory: "老祖宗把「地」上的规矩「吹」得跟「神」一样——传统。",
    example: "Many young people are losing interest in traditional customs.",
    exampleCn: "许多年轻人对传统习俗失去兴趣。",
    collocations: ["cultural tradition", "traditional (adj.)", "keep a tradition alive"] },
  { id: 57, topic: "culture", word: "preserve", ipa: "/prɪˈzɜːv/", pos: "v.", cn: "保存；保护",
    pun: "扑累者服", punStory: "pre（提前）+ serve（服务）：提前把「服」装收好，「扑」上去，「累」也要保护。",
    example: "Efforts have been made to preserve ancient buildings in the old town.",
    exampleCn: "人们努力保护老城的古建筑。",
    collocations: ["preserve traditions / culture", "preservation (n.)"] },
  { id: 58, topic: "culture", word: "diverse", ipa: "/daɪˈvɜːs/", pos: "adj.", cn: "多样的",
    pun: "带我思", punStory: "「带我」去看各种各样的世界，让我「思」考——多样的。",
    example: "London is one of the most culturally diverse cities in the world.",
    exampleCn: "伦敦是世界上文化最多元的城市之一。",
    collocations: ["culturally diverse", "diversity (n.)", "a diverse range of"] },
  { id: 59, topic: "culture", word: "advertisement", ipa: "/ədˈvɜːtɪsmənt/", pos: "n.", cn: "广告",
    pun: "爱的我提死门", punStory: "「爱的我」——广告每天「提」到你「死」，追到家「门」口。",
    example: "Advertisements aimed at children should be banned.",
    exampleCn: "针对儿童的广告应该被禁止。",
    collocations: ["advertise (v.)", "advertising (n.) 广告业", "TV / online advertisements"] },
  { id: 60, topic: "culture", word: "leisure", ipa: "/ˈleʒə(r)/", pos: "n.", cn: "休闲；空闲",
    pun: "累着", punStory: "「累着」了？那就歇一歇，享受休闲时间。",
    example: "People today have more leisure time than previous generations.",
    exampleCn: "今天的人比前几代人有更多休闲时间。",
    collocations: ["leisure time / activities", "at leisure"] },

  // ───────── 学术万能词 ─────────
  { id: 61, topic: "academic", word: "significant", ipa: "/sɪɡˈnɪfɪkənt/", pos: "adj.", cn: "重要的；显著的",
    pun: "洗个泥飞坑", punStory: "sign 是「标志」，有标志性的就是显著的。「洗个泥」也能「飞」出「坑」，很显著！",
    example: "There has been a significant increase in the number of international students.",
    exampleCn: "国际学生数量显著增加。",
    collocations: ["a significant increase / impact", "significantly (adv.)", "significance (n.)"] },
  { id: 62, topic: "academic", word: "consequently", ipa: "/ˈkɒnsɪkwəntli/", pos: "adv.", cn: "因此",
    pun: "看死快特累", punStory: "sequence 是「顺序」，跟着前面的顺序来，「因此」。熬夜「看」剧，「死快特累」，因此上课睡着。",
    example: "Fuel prices rose sharply; consequently, more people started cycling to work.",
    exampleCn: "油价大涨，因此更多人骑车上班。",
    collocations: ["consequence (n.) 后果", "as a consequence", "consequent (adj.)"] },
  { id: 63, topic: "academic", word: "phenomenon", ipa: "/fəˈnɒmɪnən/", pos: "n.", cn: "现象",
    pun: "发 no 米能", punStory: "「发」现家里「no 米」了，还「能」怎么办——先观察这个现象。",
    example: "Social media addiction is a relatively new phenomenon.",
    exampleCn: "社交媒体成瘾是一个相对较新的现象。",
    collocations: ["a common / global phenomenon", "复数 phenomena"] },
  { id: 64, topic: "academic", word: "inevitable", ipa: "/ɪnˈevɪtəbl/", pos: "adj.", cn: "不可避免的",
    pun: "一哎我躲不", punStory: "「一」看到它，「哎」，「我躲不」掉——不可避免。",
    example: "Some job losses are inevitable as industries adopt new technology.",
    exampleCn: "随着行业采用新技术，部分失业不可避免。",
    collocations: ["inevitably (adv.)", "an inevitable consequence", "it is inevitable that..."] },
  { id: 65, topic: "academic", word: "controversial", ipa: "/ˌkɒntrəˈvɜːʃl/", pos: "adj.", cn: "有争议的",
    pun: "看抓我手", punStory: "「看」，吵起来了，还「抓我手」——这话题真有争议。",
    example: "Nuclear power remains a highly controversial issue.",
    exampleCn: "核能仍是一个极具争议的问题。",
    collocations: ["a controversial issue / topic", "controversy (n.)"] },
  { id: 66, topic: "academic", word: "detrimental", ipa: "/ˌdetrɪˈmentl/", pos: "adj.", cn: "有害的",
    pun: "得追门头", punStory: "「得」（děi）「追」着人往「门头」上撞——有害。",
    example: "Excessive screen time can be detrimental to children's eyesight.",
    exampleCn: "屏幕时间过长对儿童视力有害。",
    collocations: ["detrimental to sth", "a detrimental effect / impact"] },
  { id: 67, topic: "academic", word: "alleviate", ipa: "/əˈliːvieɪt/", pos: "v.", cn: "缓解；减轻",
    pun: "饿立喂 eat", punStory: "「饿」了「立」刻「喂」你「eat」——缓解饥饿。",
    example: "Building more public housing could alleviate the housing shortage.",
    exampleCn: "建更多公共住房可以缓解住房短缺。",
    collocations: ["alleviate poverty / pressure / pain", "alleviation (n.)"] },
  { id: 68, topic: "academic", word: "prevalent", ipa: "/ˈprevələnt/", pos: "adj.", cn: "普遍的；盛行的",
    pun: "普瑞我冷特", punStory: "「普」遍「瑞」雪，「我冷特」（我特别冷）——到处都是，普遍的。",
    example: "Obesity is more prevalent in countries with a high intake of fast food.",
    exampleCn: "肥胖在快餐摄入量高的国家更普遍。",
    collocations: ["prevalent among / in", "increasingly prevalent", "prevalence (n.)"] },
  { id: 69, topic: "academic", word: "perspective", ipa: "/pəˈspektɪv/", pos: "n.", cn: "观点；视角",
    pun: "怕死派克提夫", punStory: "per（每一）+ spect（看）：每个人看的角度。「怕死」的「派克」和「提夫」看法完全不同。",
    example: "Travelling abroad gives students a broader perspective on the world.",
    exampleCn: "出国旅行让学生对世界有更广阔的视角。",
    collocations: ["from a different perspective", "put sth into perspective", "a broader perspective"] },
  { id: 70, topic: "academic", word: "hypothesis", ipa: "/haɪˈpɒθəsɪs/", pos: "n.", cn: "假设；假说",
    pun: "嗨怕什死死", punStory: "「嗨，怕什」（怕啥），「死死」地先假设一个，再去验证——假说。",
    example: "The researchers tested the hypothesis that sleep improves memory.",
    exampleCn: "研究人员检验了「睡眠改善记忆」这一假设。",
    collocations: ["test a hypothesis", "复数 hypotheses", "hypothetical (adj.)"] }
];
